version: 0.2

env:
  variables:
    PACKAGE: "golang-questionnaire"

phases:
  install:
    commands:
      - go get -u github.com/golang/lint/golint
      - go get -u ./...

  pre_build:
    commands:
      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:
      # Build our application
      - go build -o questionnaireApp

artifacts:
  files:
    - questionnaireApp
    - appspec.yml
    - buildspec.yml
    - config/*
    - codedeploy/*
    - cloudformation/*
