version: 0.2

env:
  variables:
    PACKAGE: "golang-questionnaire"

phases:

  install:
    commands:
      - echo Install in `pwd`

      - go get -u github.com/golang/dep/cmd/dep
      - go get -u github.com/golang/lint/golint

      - echo GOPATH - $GOPATH
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR

      - echo Create dir in GOPATH for sources
      - mkdir -p ${CODEBUILD_SRC_DIR}/${PACKAGE}

      - echo Copy source files into GOPATH
      - echo cp -a ${CODEBUILD_SRC_DIR}/.  ${CODEBUILD_SRC_DIR}/${PACKAGE}
      - cp -a ${CODEBUILD_SRC_DIR}/.  ${CODEBUILD_SRC_DIR}/${PACKAGE}

      - echo Install dependencies
      - cd ${CODEBUILD_SRC_DIR}/${PACKAGE} && dep ensure

  pre_build:
    commands:
      - echo Prebuild in `pwd`
      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - cd ${CODEBUILD_SRC_DIR}/${PACKAGE} && go test

  build:
    commands:
      # Build our application
      - echo Build in `pwd`
      - cd ${CODEBUILD_SRC_DIR}/${PACKAGE} && go build -o ${CODEBUILD_SRC_DIR}/questionnaireApp

artifacts:
  files:
    - questionnaireApp
    - appspec.yml
    - buildspec.yml
    - config/*
    - codedeploy/*
    - cloudformation/*
